name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-24.04
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U testuser -d testdb"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: 対象ブランチをクローン
        uses: actions/checkout@v4

      - name: Goの準備
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.5'
          cache: true
          cache-dependency-path: go.sum

      - name: テストを実行
        run: |
          cd migrate
          GO_ENV=test go run migrate.go
          cd ..
          go test ./usecase
          go test ./validator
          go test ./repository -p 1
