name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: 対象ブランチをクローン
        uses: actions/checkout@v4

      - name: Goの準備
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.5'
          cache: true
          cache-dependency-path: go.sum

      - name: テストを実行
        run: |
          go test ./usecase
